linters:
  eslint:
    config: './eslint.config'
    rubocop:
        display_cop_names: true
        # indicate where is the config file for stylelint
        config: './rubocop.yml'
        
    
files:
    ignore:
        - '.eslintrc.json' 
        - '.script.js'
        - "bin/*"
        - "db/*"
        - "config/*"
        - "Guardfile"
        - "Rakefile"
        - "README.md"
        - "node_modules/**/*"


 